// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.ComputerSelectionResult
{

    public class Data
    {

        [JsonProperty("args")]
        public Arg[] Args { get; set; }

        [JsonProperty("attribution")]
        public Attribution Attribution { get; set; }
    }

}
