// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Files
{

    public class Data
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("file")]
        public File File { get; set; }
    }

}
