// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Star
{

    public class Data
    {

        [JsonProperty("posts")]
        public Post[] Posts { get; set; }
    }

}
