// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.ComputerResult
{

    public class Args
    {

        [JsonProperty("query")]
        public string Query { get; set; }
    }

}
