// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.ComputerResult
{

    public class Data
    {

        [JsonProperty("objects")]
        public Object[] Objects { get; set; }

        [JsonProperty("args")]
        public Args Args { get; set; }
    }

}
