// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.ComputerResult
{

    public class Object
    {

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("effects")]
        public object[] Effects { get; set; }

        [JsonProperty("src")]
        public string Src { get; set; }

        [JsonProperty("scaleMode")]
        public string ScaleMode { get; set; }
    }

}
