// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Posts
{

    public class Author
    {

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("description")]
        public object Description { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("createdString")]
        public string CreatedString { get; set; }

        [JsonProperty("timeZone")]
        public string TimeZone { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

}
