// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Posts
{

    public class ForkedFrom
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("author")]
        public Author Author { get; set; }
    }

}
