// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Posts
{

    public class Object
    {

        [JsonProperty("src")]
        public string Src { get; set; }

        [JsonProperty("frame")]
        public double[] Frame { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("effects")]
        public string[] Effects { get; set; }

        [JsonProperty("color")]
        public double[] Color { get; set; }

        [JsonProperty("scaleMode")]
        public string ScaleMode { get; set; }

        [JsonProperty("bpm")]
        public int? Bpm { get; set; }

        [JsonProperty("length")]
        public int? Length { get; set; }

        [JsonProperty("instructions")]
        public object[][] Instructions { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("transform")]
        public double[][] Transform { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("attributes")]
        public object[] Attributes { get; set; }

        [JsonProperty("alignment")]
        public string Alignment { get; set; }

        [JsonProperty("size")]
        public int? Size { get; set; }
    }

}
