// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Posts
{

    public class Package
    {

        [JsonProperty("objects")]
        public Object[] Objects { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("background")]
        public double[][] Background { get; set; }
    }

}
