// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Posts
{

    public class Post
    {

        [JsonProperty("lookCount")]
        public int LookCount { get; set; }

        [JsonProperty("previewUrl")]
        public string PreviewUrl { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("comments")]
        public Comment[] Comments { get; set; }

        [JsonProperty("thumbnailSrc")]
        public string ThumbnailSrc { get; set; }

        [JsonProperty("hidden")]
        public bool Hidden { get; set; }

        [JsonProperty("boost")]
        public int Boost { get; set; }

        [JsonProperty("updated")]
        public object Updated { get; set; }

        [JsonProperty("authorType")]
        public string AuthorType { get; set; }

        [JsonProperty("deleted")]
        public bool Deleted { get; set; }

        [JsonProperty("stickersCount")]
        public int StickersCount { get; set; }

        [JsonProperty("createdString")]
        public string CreatedString { get; set; }

        [JsonProperty("favCount")]
        public int FavCount { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("thumbnails")]
        public Thumbnails Thumbnails { get; set; }

        [JsonProperty("package")]
        public Package Package { get; set; }

        [JsonProperty("ownedByUser")]
        public bool OwnedByUser { get; set; }

        [JsonProperty("created")]
        public object Created { get; set; }

        [JsonProperty("caption")]
        public string Caption { get; set; }

        [JsonProperty("updatedString")]
        public string UpdatedString { get; set; }

        [JsonProperty("commentsCount")]
        public int CommentsCount { get; set; }

        [JsonProperty("forkedFrom")]
        public ForkedFrom ForkedFrom { get; set; }
    }

}
