// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Posts
{

    public class Thumbnails
    {

        [JsonProperty("default")]
        public Default Default { get; set; }
    }

}
