// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.User
{

    public class Data
    {

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("latestMessageString")]
        public string LatestMessageString { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("devices")]
        public Device[] Devices { get; set; }

        [JsonProperty("createdString")]
        public string CreatedString { get; set; }

        [JsonProperty("userId")]
        public string UserId { get; set; }

        [JsonProperty("timeZone")]
        public string TimeZone { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("messageCount")]
        public int MessageCount { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

}
