// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.User
{

    public class Device
    {

        [JsonProperty("app_environment")]
        public string AppEnvironment { get; set; }

        [JsonProperty("token")]
        public string Token { get; set; }
    }

}
