// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Activity
{

    public class Message
    {

        [JsonProperty("comment")]
        public Comment Comment { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }
    }

}
