// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Comments
{

    public class Comment
    {

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("author")]
        public object Author { get; set; }

        [JsonProperty("point")]
        public Point Point { get; set; }

        [JsonProperty("sticker")]
        public string Sticker { get; set; }

        [JsonProperty("markup")]
        public object[] Markup { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("createdString")]
        public string CreatedString { get; set; }

        [JsonProperty("postId")]
        public string PostId { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

}
