// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace ByteSharp.Entities.Comments
{

    public class Data
    {

        [JsonProperty("comment")]
        public Comment Comment { get; set; }
    }

}
